variant: fcos
version: 1.3.0
passwd:
  users:
  - name: core
    ssh_authorized_keys:
      - ssh-rsa ...
storage:
  files:
   - path: /etc/containers/systemd/at-warrior.container
     contents:
       inline: |
         [Unit]
         Description=Archive Team Warrior Container
         After=network-online.target

         [Container]
         ContainerName=at-warrior
         Image=atdr.meo.ws/archiveteam/warrior-dockerfile
         Label=io.containers.autoupdate=registry
         Volume=at-warrior-projects:/home/warrior/projects
         Environment=SELECTED_PROJECT=auto
         Environment=DOWNLOADER=<username>

         [Install]
         WantedBy=multi-user.target
systemd:
  units:
    - name: podman-auto-update.timer
      enabled: true